[package]
name = "klipper_rust_port"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "rlib"] # staticlib for C, rlib for Rust tests/benchmarks

[dependencies]

[build-dependencies]
cbindgen = "0.29"
